# Generated by Django 5.0.6 on 2024-06-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram.userbusiness",
                        verbose_name="Бизнес пользователь",
                    ),
                ),
                (
                    "client_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram.usercklient",
                        verbose_name="Пользователь клиента",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
